const sideLinks = document.querySelectorAll('.sidebar .side-menu li a:not(.logout)');

sideLinks.forEach(item => {
    const li = item.parentElement;
    item.addEventListener('click', () => {
        sideLinks.forEach(i => {
            i.parentElement.classList.remove('active');
        })
        li.classList.add('active');
    })
});

const menuBar = document.querySelector('.content nav .bx.bx-menu');
const sideBar = document.querySelector('.sidebar');

menuBar.addEventListener('click', () => {
    sideBar.classList.toggle('close');
});

const searchBtn = document.querySelector('.content nav form .form-input button');
const searchBtnIcon = document.querySelector('.content nav form .form-input button .bx');
const searchForm = document.querySelector('.content nav form');

searchBtn.addEventListener('click', function (e) {
    if (window.innerWidth < 576) {
        e.preventDefault;
        searchForm.classList.toggle('show');
        if (searchForm.classList.contains('show')) {
            searchBtnIcon.classList.replace('bx-search', 'bx-x');
        } else {
            searchBtnIcon.classList.replace('bx-x', 'bx-search');
        }
    }
});

window.addEventListener('resize', () => {
    if (window.innerWidth < 768) {
        sideBar.classList.add('close');
    } else {
        sideBar.classList.remove('close');
    }
    if (window.innerWidth > 576) {
        searchBtnIcon.classList.replace('bx-x', 'bx-search');
        searchForm.classList.remove('show');
    }
});

const toggler = document.getElementById('theme-toggle');

toggler.addEventListener('change', function () {
    if (this.checked) {
        document.body.classList.add('dark');
    } else {
        document.body.classList.remove('dark');
    }
});
  // Pre-defined credentials (simulated)
  const users = {
    "Grace Fellowship": {
        password: "grace123", // password generated by admin
        role: "member" // can also be "church-leader"
    },
    "Hope Baptist": {
        password: "hope123", // password generated by admin
        role: "church-leader"
    }
};

// Handle form submission
document.getElementById("login-form").addEventListener("submit", function (event) {
    event.preventDefault(); // Prevent form from submitting

    // Get values from form
    const churchName = document.getElementById(".church-name").value.trim();
    const password = document.getElementById(".password").value.trim();


    // Check if the church exists
    if (users[churchName]) {
        // Check if the password is correct
        if (users[churchName].password === password) {
            // Redirect based on the role (church leader or member)
            if (users[churchName].role === "/church-leaders.html") {
              loadDashboard('/churchleaders.html'); // Load church leader's dashboard
            } else {
              loadDashboard('/members.html'); // Load member's dashboard // Redirect to the member's dashboard
            }
        } else {
            alert("Incorrect password. Please try again.");
        }
    } else {
        alert("Church name not found. Please check your entry.");
    }
});